partial:
  by: target
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
builds:
  - id: otelcol-contrib
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: s390x
    dir: _build
    binary: otelcol-contrib
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
archives:
  - id: otelcol-contrib
    builds:
      - otelcol-contrib
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
nfpms:
  - package_name: otelcol-contrib
    contents:
      - src: otelcol-contrib.service
        dst: /lib/systemd/system/otelcol-contrib.service
      - src: otelcol-contrib.conf
        dst: /etc/otelcol-contrib/otelcol-contrib.conf
        type: config|noreplace
      - src: config.yaml
        dst: /etc/otelcol-contrib/config.yaml
        type: config
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    id: otelcol-contrib
    builds:
      - otelcol-contrib
    formats:
      - apk
      - deb
      - rpm
    maintainer: The OpenTelemetry Collector maintainers <cncf-opentelemetry-maintainers@lists.cncf.io>
    description: OpenTelemetry Collector - otelcol-contrib
    license: Apache 2.0
checksum:
  name_template: '{{ .ProjectName }}_otelcol-contrib_checksums.txt'
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - flachesis/opentelemetry-collector-contrib:{{ .Version }}-amd64
      - flachesis/opentelemetry-collector-contrib:latest-amd64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - flachesis/opentelemetry-collector-contrib:{{ .Version }}-arm64
      - flachesis/opentelemetry-collector-contrib:latest-arm64
    extra_files:
      - config.yaml
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
    use: buildx
docker_manifests:
  - name_template: flachesis/opentelemetry-collector-contrib:{{ .Version }}
    image_templates:
      - flachesis/opentelemetry-collector-contrib:{{ .Version }}-amd64
      - flachesis/opentelemetry-collector-contrib:{{ .Version }}-arm64
  - name_template: flachesis/opentelemetry-collector-contrib:latest
    image_templates:
      - flachesis/opentelemetry-collector-contrib:latest-amd64
      - flachesis/opentelemetry-collector-contrib:latest-arm64
sboms:
  - id: archive
    artifacts: archive
  - id: package
    artifacts: package
